# Generated by Django 4.1.2 on 2022-10-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0002_product_productcatategory_vendorregister_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorregister',
            old_name='Business_logo',
            new_name='business_logo',
        ),
    ]
