# Generated by Django 4.1.2 on 2022-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0003_rename_business_logo_vendorregister_business_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productcatategory',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Productcatategory',
            new_name='Productcategory',
        ),
        migrations.AddField(
            model_name='vendorregister',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
